// GENERATED by `npm run build` from src/tokens.json. Do not edit by hand.
const c = (k) => `var(--m1-${k})`;
module.exports = {
  theme: {
    extend: {
      colors: {
        'm1-bg': c('bg'),
        'm1-bg2': c('bg2'),
        'm1-ink': c('ink'),
        'm1-muted': c('muted'),
        'm1-line': c('line'),
        'm1-line2': c('line2'),
        'm1-accent': c('accent'),
        'm1-accent2': c('accent2'),
        'm1-spark': c('spark'),
        'm1-pill': c('pill'),
        'm1-pillink': c('pillink'),
        'm1-ico': c('ico'),
      },
      fontFamily: {
        'm1-display': 'var(--m1-font-display)',
        'm1-accent': 'var(--m1-font-accent)',
        'm1-mono': 'var(--m1-font-mono)',
      },
      maxWidth: { 'm1-measure': 'var(--m1-measure)' },
      borderRadius: { 'm1': 'var(--m1-radius)' },
    },
  },
};
