/* Generates dist/ from src/tokens.json + src/primitives.css.
   tokens.json is the only place a colour is ever edited. */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const T = JSON.parse(readFileSync(join(root, 'src/tokens.json'), 'utf8'));
const primitives = readFileSync(join(root, 'src/primitives.css'), 'utf8');
mkdirSync(join(root, 'dist'), { recursive: true });

const pad = (s, n) => s.padEnd(n);
const varsFor = (mode) => Object.entries(T.color)
  .map(([k, v]) => `  --m1-${pad(k + ':', 9)} ${v[mode]};`).join('\n');

const fontVars = Object.entries(T.font)
  .map(([k, v]) => `  --m1-font-${pad(k + ':', 9)} ${v.stack};`).join('\n');

const css = `/* ===========================================================================
   Modus One — design system
   GENERATED by \`npm run build\` from src/tokens.json. Do not edit by hand.
   Deep Field palette · Archivo + Newsreader italic + IBM Plex Mono
   Source of truth: ${T.$meta.source}
   ===========================================================================

   Fonts — all three are on Google Fonts. Either add to <head>:
     <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
     <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Archivo:wght@400;500;700;800&family=IBM+Plex+Mono&family=Newsreader:ital,wght@1,400;1,500&display=swap">
   …or self-host. The fallback stacks below keep layout honest either way.

   Accent discipline — each does one job, and swapping them is the fastest way
   to look almost-right-but-off:
${Object.entries(T.color).filter(([k]) => ['accent','accent2','spark'].includes(k))
  .map(([k, v]) => `     --m1-${pad(k, 8)} ${v.job}`).join('\n')}
                                                                              */

:root {
${varsFor('dark')}

${fontVars}
  --m1-measure: ${T.size.measure};
  --m1-radius:  ${T.size.radius};
}

:root[data-theme="light"] {
${varsFor('light')}
}

${primitives}`;

writeFileSync(join(root, 'dist/modus-one.css'), css);

/* JS/TS consumers — React Native, canvas, charts, anything not CSS. */
const js = `// GENERATED by \`npm run build\` from src/tokens.json. Do not edit by hand.
export const color = ${JSON.stringify(
  Object.fromEntries(Object.entries(T.color).map(([k, v]) => [k, { dark: v.dark, light: v.light }])), null, 2)};

export const font = ${JSON.stringify(
  Object.fromEntries(Object.entries(T.font).map(([k, v]) => [k, v.stack])), null, 2)};

export const contrastFloor = ${T.$meta.contrastFloor};
export default { color, font, contrastFloor };
`;
writeFileSync(join(root, 'dist/tokens.js'), js);
writeFileSync(join(root, 'dist/tokens.json'), JSON.stringify(T, null, 2));

/* Tailwind users: `presets: [require('@modusone/design/tailwind')]` */
const tw = `// GENERATED by \`npm run build\` from src/tokens.json. Do not edit by hand.
const c = (k) => \`var(--m1-\${k})\`;
module.exports = {
  theme: {
    extend: {
      colors: {
${Object.keys(T.color).map(k => `        'm1-${k}': c('${k}'),`).join('\n')}
      },
      fontFamily: {
${Object.keys(T.font).map(k => `        'm1-${k}': 'var(--m1-font-${k})',`).join('\n')}
      },
      maxWidth: { 'm1-measure': 'var(--m1-measure)' },
      borderRadius: { 'm1': 'var(--m1-radius)' },
    },
  },
};
`;
writeFileSync(join(root, 'tailwind.cjs'), tw);

console.log(`built dist/modus-one.css (${css.length} bytes), dist/tokens.js, dist/tokens.json, tailwind.cjs`);
