/* Generates dist/ from src/tokens.json + src/primitives.css.
   tokens.json is the only place a colour or a motion value is ever edited. */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const T = JSON.parse(readFileSync(join(root, 'src/tokens.json'), 'utf8'));
const primitives = readFileSync(join(root, 'src/primitives.css'), 'utf8');
mkdirSync(join(root, 'dist'), { recursive: true });

const pad = (s, n) => s.padEnd(n);
const varsFor = (mode) => Object.entries(T.color)
  .map(([k, v]) => `  --m1-${pad(k + ':', 9)} ${v[mode]};`).join('\n');

const fontVars = Object.entries(T.font)
  .map(([k, v]) => `  --m1-font-${pad(k + ':', 9)} ${v.stack};`).join('\n');

/* The spatial spring, sampled into something CSS can use: a settle time and a linear() easing.
   A CSS transition can't carry velocity, so this is the spring from rest. JS consumers that
   need interruption use the stiffness/damping/mass in dist/tokens.js directly. */
function springCurve({ stiffness: k, damping: c, mass: m }) {
  const dt = 0.001, samples = [];
  let x = 0, v = 0, settle = 0;
  for (let t = dt; t <= 3; t += dt) {
    v += ((-k * (x - 1) - c * v) / m) * dt; x += v * dt;
    samples.push(x);
    if (Math.abs(x - 1) > 0.001 || Math.abs(v) > 0.01) settle = t;
  }
  const durationMs = Math.ceil(settle * 100) * 10;
  const N = 24, stops = [];
  for (let i = 0; i <= N; i++) {
    const idx = Math.round((durationMs / 1000) * (i / N) / dt) - 1;
    stops.push(i === 0 ? 0 : i === N ? 1 : +samples[idx].toFixed(3));
  }
  return { durationMs, easing: `linear(${stops.join(', ')})` };
}
const M = T.motion;
const spatial = springCurve(M.spatial);

const css = `/* ===========================================================================
   Modus One — design system
   GENERATED by \`npm run build\` from src/tokens.json. Do not edit by hand.
   Deep Field palette · Archivo + Newsreader italic + IBM Plex Mono
   Source of truth: ${T.$meta.source}
   ===========================================================================

   Fonts — all three are on Google Fonts. Either add to <head>:
     <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
     <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Archivo:wght@400;500;700;800&family=IBM+Plex+Mono&family=Newsreader:ital,wght@1,400;1,500&display=swap">
   …or self-host. The fallback stacks below keep layout honest either way.

   Accent discipline — each does one job, and swapping them is the fastest way
   to look almost-right-but-off:
${Object.entries(T.color).filter(([k]) => ['accent','accent2','spark'].includes(k))
  .map(([k, v]) => `     --m1-${pad(k, 8)} ${v.job}`).join('\n')}
                                                                              */

:root {
${varsFor('dark')}

${fontVars}
  --m1-measure: ${T.size.measure};
  --m1-radius:  ${T.size.radius};

  /* Motion: PATTERNS.md §15. spatial = position/size/shape (a spring, sampled). effects = colour/opacity. */
  --m1-dur-spatial:  ${spatial.durationMs}ms;
  --m1-ease-spatial: ${spatial.easing};
  --m1-dur-effects:  ${M.effects.durationMs}ms;
  --m1-ease-effects: ${M.effects.easing};
  --m1-dur-reduced:  ${M.reduced.durationMs}ms;
}

:root[data-theme="light"] {
${varsFor('light')}
}

${primitives}`;

writeFileSync(join(root, 'dist/modus-one.css'), css);

/* Horizon: the consumer theme. Light (Paper) on :root, dark (Forest) under [data-theme="dark"]. */
const H = T.horizon;
const kebab = (k) => k.replace(/[A-Z]/g, (m) => '-' + m.toLowerCase());
const hzVars = (mode) => Object.entries(H.color)
  .map(([k, v]) => `  --hz-${pad(kebab(k) + ':', 13)} ${v[mode]};`).join('\n');
const hzSpatial = springCurve(H.motion.spatial);
const hzCss = `/* ===========================================================================
   Modus One — Horizon (the consumer theme)
   GENERATED by \`npm run build\` from src/tokens.json. Do not edit by hand.
   Paper (light) is the default; Forest (dark) under [data-theme="dark"].

   Fonts:
     <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,400;12..96,500;12..96,700;12..96,800&family=Spline+Sans+Mono:wght@400;500&display=swap">

   Two colours carry meaning and nothing else does:
     --hz-lead    ${H.color.lead.job}
     --hz-signal  it needs you (see signal, signal-text, signal-fill)
                                                                              */

:root {
${hzVars('light')}

${Object.entries(H.font).map(([k, v]) => `  --hz-font-${pad(k + ':', 9)} ${v.stack};`).join('\n')}
  --hz-radius-card:  ${H.size.radiusCard};
  --hz-radius-field: ${H.size.radiusField};
  --hz-radius-pill:  ${H.size.radiusPill};

  --hz-dur-spatial:  ${hzSpatial.durationMs}ms;
  --hz-ease-spatial: ${hzSpatial.easing};
  --hz-dur-effects:  ${H.motion.effects.durationMs}ms;
  --hz-ease-effects: ${H.motion.effects.easing};
  --hz-dur-reduced:  ${H.motion.reduced.durationMs}ms;
}

:root[data-theme="dark"] {
${hzVars('dark')}
}
`;
writeFileSync(join(root, 'dist/horizon.css'), hzCss);

/* JS/TS consumers — React Native, canvas, charts, anything not CSS. */
const js = `// GENERATED by \`npm run build\` from src/tokens.json. Do not edit by hand.
export const color = ${JSON.stringify(
  Object.fromEntries(Object.entries(T.color).map(([k, v]) => [k, { dark: v.dark, light: v.light }])), null, 2)};

export const font = ${JSON.stringify(
  Object.fromEntries(Object.entries(T.font).map(([k, v]) => [k, v.stack])), null, 2)};

export const motion = ${JSON.stringify({
  spatial: { stiffness: M.spatial.stiffness, damping: M.spatial.damping, mass: M.spatial.mass, durationMs: spatial.durationMs, easing: spatial.easing },
  effects: { durationMs: M.effects.durationMs, easing: M.effects.easing },
  reduced: { durationMs: M.reduced.durationMs, easing: M.reduced.easing },
}, null, 2)};

export const horizon = ${JSON.stringify({
  color: Object.fromEntries(Object.entries(H.color).map(([k, v]) => [k, { light: v.light, dark: v.dark }])),
  font: Object.fromEntries(Object.entries(H.font).map(([k, v]) => [k, v.stack])),
  size: H.size,
  motion: {
    spatial: { stiffness: H.motion.spatial.stiffness, damping: H.motion.spatial.damping, mass: H.motion.spatial.mass, durationMs: hzSpatial.durationMs, easing: hzSpatial.easing },
    effects: { durationMs: H.motion.effects.durationMs, easing: H.motion.effects.easing },
    reduced: { durationMs: H.motion.reduced.durationMs, easing: H.motion.reduced.easing },
  },
  logo: { grid: H.logo.grid, ringRadius: H.logo.ringRadius, ringStroke: H.logo.ringStroke, dotRadius: H.logo.dotRadius },
}, null, 2)};

export const contrastFloor = ${T.$meta.contrastFloor};
export default { color, font, motion, horizon, contrastFloor };
`;
writeFileSync(join(root, 'dist/tokens.js'), js);
writeFileSync(join(root, 'dist/tokens.json'), JSON.stringify(T, null, 2));

/* Tailwind users: `presets: [require('@modusone/design/tailwind')]` */
const tw = `// GENERATED by \`npm run build\` from src/tokens.json. Do not edit by hand.
const c = (k) => \`var(--m1-\${k})\`;
module.exports = {
  theme: {
    extend: {
      colors: {
${Object.keys(T.color).map(k => `        'm1-${k}': c('${k}'),`).join('\n')}
      },
      fontFamily: {
${Object.keys(T.font).map(k => `        'm1-${k}': 'var(--m1-font-${k})',`).join('\n')}
      },
      maxWidth: { 'm1-measure': 'var(--m1-measure)' },
      borderRadius: { 'm1': 'var(--m1-radius)' },
      transitionDuration: { 'm1-spatial': 'var(--m1-dur-spatial)', 'm1-effects': 'var(--m1-dur-effects)', 'm1-reduced': 'var(--m1-dur-reduced)' },
      transitionTimingFunction: { 'm1-spatial': 'var(--m1-ease-spatial)', 'm1-effects': 'var(--m1-ease-effects)' },
    },
  },
};
`;
writeFileSync(join(root, 'tailwind.cjs'), tw);

console.log(`built dist/modus-one.css (${css.length} bytes), dist/horizon.css (${hzCss.length} bytes), dist/tokens.js, dist/tokens.json, tailwind.cjs`);
